################################################## 
# Authentication_messages.py 
# generated by ZSI.generate.wsdl2python
##################################################


from Authentication_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

GetParametersSoapIn = upsidewireless_com_webservice_authentication.GetParameters().pyclass

GetParametersSoapOut = upsidewireless_com_webservice_authentication.GetParametersResponse().pyclass
