################################################## 
# Authentication_client.py 
# generated by ZSI.generate.wsdl2python
##################################################



import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

from Authentication_messages import GetParametersSoapIn, GetParametersSoapOut

# Locator
class AuthenticationLocator:
    AuthenticationSoap_address = "http://api.upsidewireless.com/soap/Authentication.asmx"
    def getAuthenticationSoapAddress(self):
        return AuthenticationLocator.AuthenticationSoap_address
    def getAuthenticationSoap(self, url=None, **kw):
        return AuthenticationSoapSOAP(url or AuthenticationLocator.AuthenticationSoap_address, **kw)

# Methods
class AuthenticationSoapSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: <ZSI.wstools.WSDLTools.Message instance at 0x12d2148>
    def GetParameters(self, username,password):

        request = GetParametersSoapIn()
        request.username = username
        request.password = password

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://upsidewireless.com/webservice/authentication/GetParameters", **kw)
        # no output wsaction
        response = self.binding.Receive(GetParametersSoapOut.typecode)
        GetParametersResult = response.GetParametersResult
        return GetParametersResult
