################################################## 
# SMS_messages.py 
# generated by ZSI.generate.wsdl2python
##################################################


from SMS_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

Send_TestSoapIn = upsidewireless_com_webservice_sms.Send_Test().pyclass

Send_TestSoapOut = upsidewireless_com_webservice_sms.Send_TestResponse().pyclass

Send_PlainSoapIn = upsidewireless_com_webservice_sms.Send_Plain().pyclass

Send_PlainSoapOut = upsidewireless_com_webservice_sms.Send_PlainResponse().pyclass

Send_Plain_DedicatedSoapIn = upsidewireless_com_webservice_sms.Send_Plain_Dedicated().pyclass

Send_Plain_DedicatedSoapOut = upsidewireless_com_webservice_sms.Send_Plain_DedicatedResponse().pyclass

Send_Plain_DeferredSoapIn = upsidewireless_com_webservice_sms.Send_Plain_Deferred().pyclass

Send_Plain_DeferredSoapOut = upsidewireless_com_webservice_sms.Send_Plain_DeferredResponse().pyclass

Send_FlashSoapIn = upsidewireless_com_webservice_sms.Send_Flash().pyclass

Send_FlashSoapOut = upsidewireless_com_webservice_sms.Send_FlashResponse().pyclass

Send_WAPPushSoapIn = upsidewireless_com_webservice_sms.Send_WAPPush().pyclass

Send_WAPPushSoapOut = upsidewireless_com_webservice_sms.Send_WAPPushResponse().pyclass
