################################################## 
# SMS_client.py 
# generated by ZSI.generate.wsdl2python
##################################################



import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

from SMS_messages import *

# Locator
class SMSLocator:
    SMSSoap_address = "http://api.upsidewireless.com/soap/SMS.asmx"
    def getSMSSoapAddress(self):
        return SMSLocator.SMSSoap_address
    def getSMSSoap(self, url=None, **kw):
        return SMSSoapSOAP(url or SMSLocator.SMSSoap_address, **kw)

# Methods
class SMSSoapSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: <ZSI.wstools.WSDLTools.Message instance at 0x13a9df0>
    def Send_Test(self, token,signature,recipient,message,encoding):

        request = Send_TestSoapIn()
        request.token = token
        request.signature = signature
        request.recipient = recipient
        request.message = message
        request.encoding = encoding

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://upsidewireless.com/webservice/sms/Send_Test", **kw)
        # no output wsaction
        response = self.binding.Receive(Send_TestSoapOut.typecode)
        Send_TestResult = response.Send_TestResult
        return Send_TestResult

    # op: <ZSI.wstools.WSDLTools.Message instance at 0x13a9cd8>
    def Send_Plain(self, token,signature,recipient,message,encoding):

        request = Send_PlainSoapIn()
        request.token = token
        request.signature = signature
        request.recipient = recipient
        request.message = message
        request.encoding = encoding

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://upsidewireless.com/webservice/sms/Send_Plain", **kw)
        # no output wsaction
        response = self.binding.Receive(Send_PlainSoapOut.typecode)
        Send_PlainResult = response.Send_PlainResult
        return Send_PlainResult

    # op: <ZSI.wstools.WSDLTools.Message instance at 0x13b6a80>
    def Send_Plain_Dedicated(self, token,signature,recipient,message,encoding,carrierCode,dedicatedNumber,tariff):

        request = Send_Plain_DedicatedSoapIn()
        request.token = token
        request.signature = signature
        request.recipient = recipient
        request.message = message
        request.encoding = encoding
        request.carrierCode = carrierCode
        request.dedicatedNumber = dedicatedNumber
        request.tariff = tariff

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://upsidewireless.com/webservice/sms/Send_Plain_Dedicated", **kw)
        # no output wsaction
        response = self.binding.Receive(Send_Plain_DedicatedSoapOut.typecode)
        Send_Plain_DedicatedResult = response.Send_Plain_DedicatedResult
        return Send_Plain_DedicatedResult

    # op: <ZSI.wstools.WSDLTools.Message instance at 0x13b6c60>
    def Send_Plain_Deferred(self, token,signature,recipient,message,encoding,DelayHours,DelayMinutes,label):

        request = Send_Plain_DeferredSoapIn()
        request.token = token
        request.signature = signature
        request.recipient = recipient
        request.message = message
        request.encoding = encoding
        request.DelayHours = DelayHours
        request.DelayMinutes = DelayMinutes
        request.label = label

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://upsidewireless.com/webservice/sms/Send_Plain_Deferred", **kw)
        # no output wsaction
        response = self.binding.Receive(Send_Plain_DeferredSoapOut.typecode)
        Send_Plain_DeferredResult = response.Send_Plain_DeferredResult
        return Send_Plain_DeferredResult

    # op: <ZSI.wstools.WSDLTools.Message instance at 0x13b6e40>
    def Send_Flash(self, token,signature,recipient,message):

        request = Send_FlashSoapIn()
        request.token = token
        request.signature = signature
        request.recipient = recipient
        request.message = message

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://upsidewireless.com/webservice/sms/Send_Flash", **kw)
        # no output wsaction
        response = self.binding.Receive(Send_FlashSoapOut.typecode)
        Send_FlashResult = response.Send_FlashResult
        return Send_FlashResult

    # op: <ZSI.wstools.WSDLTools.Message instance at 0x13bc080>
    def Send_WAPPush(self, token,signature,recipient,title,url):

        request = Send_WAPPushSoapIn()
        request.token = token
        request.signature = signature
        request.recipient = recipient
        request.title = title
        request.url = url

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://upsidewireless.com/webservice/sms/Send_WAPPush", **kw)
        # no output wsaction
        response = self.binding.Receive(Send_WAPPushSoapOut.typecode)
        Send_WAPPushResult = response.Send_WAPPushResult
        return Send_WAPPushResult
